-- Revert: schemas/agentic_db_storage_public/tables/upload_requests/triggers/upload_requests_force_current_user_actor_id_tg


DROP TRIGGER upload_requests_force_current_user_actor_id_tg ON agentic_db_storage_public.upload_requests;


