-- Verify: schemas/agentic_db_profiles_public/tables/app_profile_definition_grants/indexes/app_profile_definition_grants_grantor_id_idx


SELECT verify_index('agentic_db_profiles_public.app_profile_definition_grants', 'app_profile_definition_grants_grantor_id_idx');


