-- Verify: schemas/agentic_db_profiles_public/tables/app_profile_definition_grants/triggers/app_profile_definition_grants_apply_trg


SELECT verify_trigger('agentic_db_profiles_public.app_profile_definition_grants_apply_trg');


