-- Verify: schemas/agentic_db_app_public/tables/autonomy_record_chunks/triggers/autonomy_record_chunks_enqueue_embedding_insert_tg


SELECT verify_trigger('agentic_db_app_public.autonomy_record_chunks_enqueue_embedding_insert_tg');


