-- Revert: schemas/agentic_db_app_public/tables/activity_log_chunks/indexes/activity_log_chunks_embedding_text_bm25_idx


DROP INDEX agentic_db_app_public.activity_log_chunks_embedding_text_bm25_idx;


