-- Revert: schemas/agentic_db_status_public/tables/org_level_requirements/indexes/org_level_requirements_name_level_priority_idx


DROP INDEX "agentic_db_status_public".org_level_requirements_name_level_priority_idx;


