#!/usr/bin/env bash
#
# extract-avengers-fixtures.sh
#
# Extracts INSERT statements from an Avengers pg_dump and optionally
# replaces entity_id values for import into Agent OS V2.
#
# Usage:
#   ./extract-avengers-fixtures.sh [DUMP_FILE] [OUTPUT_DIR] [NEW_ENTITY_ID]
#
# Defaults:
#   DUMP_FILE      = ~/DatabaseBackups/avengers/avengers_20260304_151853.sql
#   OUTPUT_DIR     = ./fixtures
#   NEW_ENTITY_ID  = (none, no replacement)
#
# What it does:
#   1. Creates a temp database (avengers_fixture_tmp)
#   2. Restores the dump into it
#   3. Extracts INSERT statements per schema using pg_dump --column-inserts
#   4. If NEW_ENTITY_ID is set, replaces all old entity_id values
#   5. Drops the temp database
#
# Requirements: psql, pg_dump, createdb, dropdb
#

set -euo pipefail

DUMP_FILE="${1:-$HOME/DatabaseBackups/avengers/avengers_20260304_151853.sql}"
OUTPUT_DIR="${2:-./fixtures}"
NEW_ENTITY_ID="${3:-}"

TEMP_DB="avengers_fixture_tmp"
export PGHOST="${PGHOST:-localhost}"
export PGPORT="${PGPORT:-5432}"
export PGUSER="${PGUSER:-postgres}"
export PGPASSWORD="${PGPASSWORD:-password}"

# Schemas we care about (skip pgpm_migrate, raw, legacy, etc.)
SCHEMAS=(
  crm
  agent
  calendar
  email
  kb
  outbox
  accounting
  codebase
  code
  self_talk
  smart_home
)

log() { echo ">>> $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

# -------------------------------------------------------------------
# Preflight
# -------------------------------------------------------------------
[[ -f "$DUMP_FILE" ]] || die "Dump file not found: $DUMP_FILE"
command -v psql >/dev/null || die "psql not found"
command -v pg_dump >/dev/null || die "pg_dump not found"

mkdir -p "$OUTPUT_DIR"

# -------------------------------------------------------------------
# 1. Create temp DB and restore
# -------------------------------------------------------------------
log "Dropping temp DB if exists..."
dropdb --if-exists "$TEMP_DB" 2>/dev/null || true

log "Creating temp DB: $TEMP_DB"
createdb "$TEMP_DB"

log "Restoring dump into $TEMP_DB (this may take a minute)..."
psql -d "$TEMP_DB" -f "$DUMP_FILE" -q --set ON_ERROR_STOP=off 2>&1 \
  | grep -v "^SET$\|^CREATE\|^ALTER\|^COMMENT\|^GRANT\|^REVOKE\|^$" \
  | tail -5

log "Restore complete."

# -------------------------------------------------------------------
# 2. Extract INSERT statements per schema
# -------------------------------------------------------------------
for schema in "${SCHEMAS[@]}"; do
  # Check if schema exists in the restored DB
  exists=$(psql -d "$TEMP_DB" -tAc \
    "SELECT 1 FROM information_schema.schemata WHERE schema_name='$schema'" 2>/dev/null || true)

  if [[ "$exists" != "1" ]]; then
    log "Skipping $schema (not found in dump)"
    continue
  fi

  outfile="$OUTPUT_DIR/${schema}_fixtures.sql"
  log "Extracting $schema → $outfile"

  pg_dump -d "$TEMP_DB" \
    --schema="$schema" \
    --data-only \
    --column-inserts \
    --no-owner \
    --no-privileges \
    --no-comments \
    > "$outfile" 2>/dev/null

  # Count INSERT lines
  count=$(grep -c "^INSERT" "$outfile" 2>/dev/null || echo 0)
  log "  → $count INSERT statements"

  # Remove empty fixture files
  if [[ "$count" -eq 0 ]]; then
    rm "$outfile"
    log "  → (removed empty file)"
  fi
done

# -------------------------------------------------------------------
# 3. Replace entity_id if requested
# -------------------------------------------------------------------
if [[ -n "$NEW_ENTITY_ID" ]]; then
  log "Replacing entity_id values with $NEW_ENTITY_ID ..."

  # Discover all old entity_id values across all fixture files
  # (grab UUIDs that appear in entity_id columns)
  old_ids=$(grep -h "entity_id" "$OUTPUT_DIR"/*_fixtures.sql 2>/dev/null \
    | grep -oE "'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'" \
    | sort -u \
    | tr -d "'" || true)

  if [[ -z "$old_ids" ]]; then
    log "  No entity_id values found in fixtures (avengers tables may not have entity_id)."
  else
    for old_id in $old_ids; do
      if [[ "$old_id" != "$NEW_ENTITY_ID" ]]; then
        log "  Replacing $old_id → $NEW_ENTITY_ID"
        perl -pi -e "s/$old_id/$NEW_ENTITY_ID/g" "$OUTPUT_DIR"/*_fixtures.sql
      fi
    done
  fi
fi

# -------------------------------------------------------------------
# 4. Generate a combined all-fixtures file with dependency ordering
# -------------------------------------------------------------------
COMBINED="$OUTPUT_DIR/all_fixtures.sql"
log "Generating combined file: $COMBINED"
cat > "$COMBINED" <<'HEADER'
-- =============================================================
-- Avengers Database Fixtures
-- Auto-generated by extract-avengers-fixtures.sh
-- =============================================================
BEGIN;
HEADER

for f in "$OUTPUT_DIR"/*_fixtures.sql; do
  [[ "$(basename "$f")" == "all_fixtures.sql" ]] && continue
  [[ -f "$f" ]] || continue
  schema_name=$(basename "$f" _fixtures.sql)
  echo "" >> "$COMBINED"
  echo "-- ============ $schema_name ============" >> "$COMBINED"
  # Extract only INSERT lines (skip SET/SELECT pg_catalog stuff)
  grep "^INSERT" "$f" >> "$COMBINED" || true
done

echo "" >> "$COMBINED"
echo "COMMIT;" >> "$COMBINED"

combined_count=$(grep -c "^INSERT" "$COMBINED" 2>/dev/null || echo 0)
log "Combined: $combined_count total INSERTs"

# -------------------------------------------------------------------
# 5. Cleanup temp DB
# -------------------------------------------------------------------
log "Dropping temp DB: $TEMP_DB"
dropdb "$TEMP_DB" 2>/dev/null || true

log "Done! Fixtures in: $OUTPUT_DIR/"
ls -lh "$OUTPUT_DIR"/*.sql
