-- Revert: schemas/agent_db_memberships_public/tables/org_memberships/triggers/_00015_org_memberships_profile_sync_itrg


DROP TRIGGER _00015_org_memberships_profile_sync_itrg ON agent_db_memberships_public.org_memberships;


