-- Revert: schemas/agentic_db_app_public/tables/itinerary_items_chunks/constraints/itinerary_items_chunks_itinerary_items_id_fkey/constraint


ALTER TABLE agentic_db_app_public.itinerary_items_chunks 
  DROP CONSTRAINT itinerary_items_chunks_itinerary_items_id_fkey;


