-- Revert: schemas/agentic_db_app_public/tables/runtime_state_dependencies/indexes/runtime_state_dependencies_dependency_id_idx


DROP INDEX agentic_db_app_public.runtime_state_dependencies_dependency_id_idx;


