-- Revert: schemas/agentic_db_profiles_public/tables/app_profile_definition_grants/indexes/app_profile_definition_grants_permission_id_idx


DROP INDEX "agentic_db_profiles_public".app_profile_definition_grants_permission_id_idx;


