-- Revert: schemas/agentic_db_app_public/tables/autonomy_record_chunks/triggers/autonomy_record_chunks_enqueue_embedding_update_tg


DROP TRIGGER autonomy_record_chunks_enqueue_embedding_update_tg ON "agentic_db_app_public".autonomy_record_chunks;


