-- Revert: schemas/agentic_db_profiles_public/tables/org_profile_permissions/indexes/org_profile_permissions_permission_id_idx


DROP INDEX agentic_db_profiles_public.org_profile_permissions_permission_id_idx;


