-- Revert: schemas/agent_db_profiles_public/tables/app_profile_permissions/indexes/app_profile_permissions_profile_id_idx


DROP INDEX agent_db_profiles_public.app_profile_permissions_profile_id_idx;


