-- Revert: schemas/agentic_db_app_public/tables/calendar_events_chunks/constraints/calendar_events_chunks_calendar_events_id_fkey/constraint


ALTER TABLE agentic_db_app_public.calendar_events_chunks 
  DROP CONSTRAINT calendar_events_chunks_calendar_events_id_fkey;


