-- Revert: schemas/agent_db_profiles_public/tables/org_profile_definition_grants/indexes/org_profile_definition_grants_updated_at_idx


DROP INDEX agent_db_profiles_public.org_profile_definition_grants_updated_at_idx;


