-- Revert: schemas/agentic_db_app_public/tables/runtime_log_chunks/triggers/runtime_log_chunks_enqueue_embedding_insert_tg


DROP TRIGGER runtime_log_chunks_enqueue_embedding_insert_tg ON agentic_db_app_public.runtime_log_chunks;


