-- Revert: schemas/agentic_db_memberships_public/tables/org_memberships/triggers/_00020_org_validate_not_in_hierarchy


DROP TRIGGER _00020_org_validate_not_in_hierarchy ON agentic_db_memberships_public.org_memberships;


