-- Revert: schemas/agentic_db_app_public/tables/calendar_events/triggers/calendar_events_embedding_auto_updated_at_tg


DROP TRIGGER calendar_events_embedding_auto_updated_at_tg ON agentic_db_app_public.calendar_events;


