-- Revert: schemas/agentic_db_app_public/tables/agent_task_chunks/triggers/agent_task_chunks_enqueue_embedding_insert_tg


DROP TRIGGER agent_task_chunks_enqueue_embedding_insert_tg ON agentic_db_app_public.agent_task_chunks;


