-- Revert: schemas/agentic_db_profiles_public/tables/org_profile_permissions/constraints/org_profile_permissions_profile_id_permission_id_key/constraint


ALTER TABLE agentic_db_profiles_public.org_profile_permissions 
  DROP CONSTRAINT org_profile_permissions_profile_id_permission_id_key;


