-- Revert: schemas/agentic_db_app_public/tables/autonomy_records/triggers/autonomy_records_embedding_auto_updated_at_tg


DROP TRIGGER autonomy_records_embedding_auto_updated_at_tg ON agentic_db_app_public.autonomy_records;


