-- Revert: schemas/agentic_db_app_public/tables/autonomy_records/triggers/autonomy_records_enqueue_embedding_update_tg


DROP TRIGGER autonomy_records_enqueue_embedding_update_tg ON agentic_db_app_public.autonomy_records;


