-- Verify: schemas/agent_db_profiles_public/tables/org_profile_definition_grants/indexes/org_profile_definition_grants_permission_id_idx


SELECT verify_index('agent_db_profiles_public.org_profile_definition_grants', 'org_profile_definition_grants_permission_id_idx');


