-- Revert: schemas/agentic_db_app_public/tables/autonomy_record_links/indexes/autonomy_record_links_target_record_id_idx


DROP INDEX agentic_db_app_public.autonomy_record_links_target_record_id_idx;


