-- Revert: schemas/agent_db_memberships_public/tables/org_chart_edge_grants/indexes/org_chart_edge_grants_grantor_id_idx


DROP INDEX agent_db_memberships_public.org_chart_edge_grants_grantor_id_idx;


