-- Revert: schemas/agentic_db_app_public/tables/interaction_chunks/triggers/interaction_chunks_enqueue_embedding_insert_tg


DROP TRIGGER interaction_chunks_enqueue_embedding_insert_tg ON agentic_db_app_public.interaction_chunks;


