-- Revert: schemas/agentic_db_memberships_private/tables/app_memberships_sprt/indexes/app_memberships_sprts_is_owner_idx


DROP INDEX agentic_db_memberships_private.app_memberships_sprts_is_owner_idx;


