-- Revert: schemas/agentic_db_app_public/tables/raw_message_attachments/indexes/raw_message_attachments_raw_message_id_idx


DROP INDEX agentic_db_app_public.raw_message_attachments_raw_message_id_idx;


