-- Revert: schemas/agentic_db_app_public/tables/autonomy_records_chunks/indexes/autonomy_records_chunks_autonomy_record_id_idx


DROP INDEX agentic_db_app_public.autonomy_records_chunks_autonomy_record_id_idx;


