-- Verify: schemas/agentic_db_profiles_public/tables/org_profile_definition_grants/triggers/org_profile_definition_grants_apply_trg


SELECT verify_trigger('agentic_db_profiles_public.org_profile_definition_grants_apply_trg');


