/**
 * ORM Client - createClient factory
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from './client';
import type { OrmClientConfig } from './client';
import { OrgGetManagersRecordModel } from './models/orgGetManagersRecord';
import { OrgGetSubordinatesRecordModel } from './models/orgGetSubordinatesRecord';
import { AppPermissionModel } from './models/appPermission';
import { AppProfilePermissionModel } from './models/appProfilePermission';
import { AppMembershipModel } from './models/appMembership';
import { DatabaseModel } from './models/database';
import { SchemaModel } from './models/schema';
import { TableModel } from './models/table';
import { CheckConstraintModel } from './models/checkConstraint';
import { FieldModel } from './models/field';
import { ForeignKeyConstraintModel } from './models/foreignKeyConstraint';
import { FullTextSearchModel } from './models/fullTextSearch';
import { IndexModel } from './models/index';
import { LimitFunctionModel } from './models/limitFunction';
import { PolicyModel } from './models/policy';
import { PrimaryKeyConstraintModel } from './models/primaryKeyConstraint';
import { TableGrantModel } from './models/tableGrant';
import { TriggerModel } from './models/trigger';
import { UniqueConstraintModel } from './models/uniqueConstraint';
import { ViewModel } from './models/view';
import { ViewTableModel } from './models/viewTable';
import { ViewGrantModel } from './models/viewGrant';
import { ViewRuleModel } from './models/viewRule';
import { TableModuleModel } from './models/tableModule';
import { TableTemplateModuleModel } from './models/tableTemplateModule';
import { SecureTableProvisionModel } from './models/secureTableProvision';
import { RelationProvisionModel } from './models/relationProvision';
import { SchemaGrantModel } from './models/schemaGrant';
import { ApiSchemaModel } from './models/apiSchema';
import { ApiModuleModel } from './models/apiModule';
import { DomainModel } from './models/domain';
import { SiteMetadatumModel } from './models/siteMetadatum';
import { SiteModuleModel } from './models/siteModule';
import { SiteThemeModel } from './models/siteTheme';
import { ProcedureModel } from './models/procedure';
import { TriggerFunctionModel } from './models/triggerFunction';
import { ApiModel } from './models/api';
import { SiteModel } from './models/site';
import { AppModel } from './models/app';
import { ConnectedAccountsModuleModel } from './models/connectedAccountsModule';
import { CryptoAddressesModuleModel } from './models/cryptoAddressesModule';
import { CryptoAuthModuleModel } from './models/cryptoAuthModule';
import { DefaultIdsModuleModel } from './models/defaultIdsModule';
import { DenormalizedTableFieldModel } from './models/denormalizedTableField';
import { EmailsModuleModel } from './models/emailsModule';
import { EncryptedSecretsModuleModel } from './models/encryptedSecretsModule';
import { FieldModuleModel } from './models/fieldModule';
import { InvitesModuleModel } from './models/invitesModule';
import { LevelsModuleModel } from './models/levelsModule';
import { LimitsModuleModel } from './models/limitsModule';
import { MembershipTypesModuleModel } from './models/membershipTypesModule';
import { MembershipsModuleModel } from './models/membershipsModule';
import { PermissionsModuleModel } from './models/permissionsModule';
import { PhoneNumbersModuleModel } from './models/phoneNumbersModule';
import { ProfilesModuleModel } from './models/profilesModule';
import { RlsModuleModel } from './models/rlsModule';
import { SecretsModuleModel } from './models/secretsModule';
import { SessionsModuleModel } from './models/sessionsModule';
import { UserAuthModuleModel } from './models/userAuthModule';
import { UsersModuleModel } from './models/usersModule';
import { UuidModuleModel } from './models/uuidModule';
import { DatabaseProvisionModuleModel } from './models/databaseProvisionModule';
import { AppAdminGrantModel } from './models/appAdminGrant';
import { AppOwnerGrantModel } from './models/appOwnerGrant';
import { AppGrantModel } from './models/appGrant';
import { OrgMembershipModel } from './models/orgMembership';
import { OrgProfilePermissionModel } from './models/orgProfilePermission';
import { OrgProfileDefinitionGrantModel } from './models/orgProfileDefinitionGrant';
import { OrgProfileGrantModel } from './models/orgProfileGrant';
import { OrgMemberModel } from './models/orgMember';
import { OrgAdminGrantModel } from './models/orgAdminGrant';
import { OrgOwnerGrantModel } from './models/orgOwnerGrant';
import { OrgGrantModel } from './models/orgGrant';
import { OrgChartEdgeModel } from './models/orgChartEdge';
import { OrgChartEdgeGrantModel } from './models/orgChartEdgeGrant';
import { AppLimitModel } from './models/appLimit';
import { OrgLimitModel } from './models/orgLimit';
import { AppStepModel } from './models/appStep';
import { AppAchievementModel } from './models/appAchievement';
import { AppProfileGrantModel } from './models/appProfileGrant';
import { AppProfileDefinitionGrantModel } from './models/appProfileDefinitionGrant';
import { OrgProfileModel } from './models/orgProfile';
import { InviteModel } from './models/invite';
import { ClaimedInviteModel } from './models/claimedInvite';
import { OrgInviteModel } from './models/orgInvite';
import { OrgClaimedInviteModel } from './models/orgClaimedInvite';
import { OrgPermissionModel } from './models/orgPermission';
import { AppLevelRequirementModel } from './models/appLevelRequirement';
import { AppPermissionDefaultModel } from './models/appPermissionDefault';
import { RoleTypeModel } from './models/roleType';
import { OrgPermissionDefaultModel } from './models/orgPermissionDefault';
import { CryptoAddressModel } from './models/cryptoAddress';
import { AppLimitDefaultModel } from './models/appLimitDefault';
import { OrgLimitDefaultModel } from './models/orgLimitDefault';
import { ConnectedAccountModel } from './models/connectedAccount';
import { PhoneNumberModel } from './models/phoneNumber';
import { MembershipTypeModel } from './models/membershipType';
import { AppMembershipDefaultModel } from './models/appMembershipDefault';
import { NodeTypeRegistryModel } from './models/nodeTypeRegistry';
import { OrgMembershipDefaultModel } from './models/orgMembershipDefault';
import { AuditLogModel } from './models/auditLog';
import { AppLevelModel } from './models/appLevel';
import { EmailModel } from './models/email';
import { AppProfileModel } from './models/appProfile';
import { UserModel } from './models/user';
import { HierarchyModuleModel } from './models/hierarchyModule';
import { createQueryOperations } from './query';
import { createMutationOperations } from './mutation';
export type { OrmClientConfig, QueryResult, GraphQLError, GraphQLAdapter } from './client';
export { GraphQLRequestError } from './client';
export { QueryBuilder } from './query-builder';
export * from './select-types';
export * from './models';
export { createQueryOperations } from './query';
export { createMutationOperations } from './mutation';
/**
 * Create an ORM client instance
 *
 * @example
 * ```typescript
 * const db = createClient({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer token' },
 * });
 *
 * // Query users
 * const users = await db.user.findMany({
 *   select: { id: true, name: true },
 *   first: 10,
 * }).execute();
 *
 * // Create a user
 * const newUser = await db.user.create({
 *   data: { name: 'John', email: 'john@example.com' },
 *   select: { id: true },
 * }).execute();
 * ```
 */
export function createClient(config: OrmClientConfig) {
  const client = new OrmClient(config);
  return {
    orgGetManagersRecord: new OrgGetManagersRecordModel(client),
    orgGetSubordinatesRecord: new OrgGetSubordinatesRecordModel(client),
    appPermission: new AppPermissionModel(client),
    appProfilePermission: new AppProfilePermissionModel(client),
    appMembership: new AppMembershipModel(client),
    database: new DatabaseModel(client),
    schema: new SchemaModel(client),
    table: new TableModel(client),
    checkConstraint: new CheckConstraintModel(client),
    field: new FieldModel(client),
    foreignKeyConstraint: new ForeignKeyConstraintModel(client),
    fullTextSearch: new FullTextSearchModel(client),
    index: new IndexModel(client),
    limitFunction: new LimitFunctionModel(client),
    policy: new PolicyModel(client),
    primaryKeyConstraint: new PrimaryKeyConstraintModel(client),
    tableGrant: new TableGrantModel(client),
    trigger: new TriggerModel(client),
    uniqueConstraint: new UniqueConstraintModel(client),
    view: new ViewModel(client),
    viewTable: new ViewTableModel(client),
    viewGrant: new ViewGrantModel(client),
    viewRule: new ViewRuleModel(client),
    tableModule: new TableModuleModel(client),
    tableTemplateModule: new TableTemplateModuleModel(client),
    secureTableProvision: new SecureTableProvisionModel(client),
    relationProvision: new RelationProvisionModel(client),
    schemaGrant: new SchemaGrantModel(client),
    apiSchema: new ApiSchemaModel(client),
    apiModule: new ApiModuleModel(client),
    domain: new DomainModel(client),
    siteMetadatum: new SiteMetadatumModel(client),
    siteModule: new SiteModuleModel(client),
    siteTheme: new SiteThemeModel(client),
    procedure: new ProcedureModel(client),
    triggerFunction: new TriggerFunctionModel(client),
    api: new ApiModel(client),
    site: new SiteModel(client),
    app: new AppModel(client),
    connectedAccountsModule: new ConnectedAccountsModuleModel(client),
    cryptoAddressesModule: new CryptoAddressesModuleModel(client),
    cryptoAuthModule: new CryptoAuthModuleModel(client),
    defaultIdsModule: new DefaultIdsModuleModel(client),
    denormalizedTableField: new DenormalizedTableFieldModel(client),
    emailsModule: new EmailsModuleModel(client),
    encryptedSecretsModule: new EncryptedSecretsModuleModel(client),
    fieldModule: new FieldModuleModel(client),
    invitesModule: new InvitesModuleModel(client),
    levelsModule: new LevelsModuleModel(client),
    limitsModule: new LimitsModuleModel(client),
    membershipTypesModule: new MembershipTypesModuleModel(client),
    membershipsModule: new MembershipsModuleModel(client),
    permissionsModule: new PermissionsModuleModel(client),
    phoneNumbersModule: new PhoneNumbersModuleModel(client),
    profilesModule: new ProfilesModuleModel(client),
    rlsModule: new RlsModuleModel(client),
    secretsModule: new SecretsModuleModel(client),
    sessionsModule: new SessionsModuleModel(client),
    userAuthModule: new UserAuthModuleModel(client),
    usersModule: new UsersModuleModel(client),
    uuidModule: new UuidModuleModel(client),
    databaseProvisionModule: new DatabaseProvisionModuleModel(client),
    appAdminGrant: new AppAdminGrantModel(client),
    appOwnerGrant: new AppOwnerGrantModel(client),
    appGrant: new AppGrantModel(client),
    orgMembership: new OrgMembershipModel(client),
    orgProfilePermission: new OrgProfilePermissionModel(client),
    orgProfileDefinitionGrant: new OrgProfileDefinitionGrantModel(client),
    orgProfileGrant: new OrgProfileGrantModel(client),
    orgMember: new OrgMemberModel(client),
    orgAdminGrant: new OrgAdminGrantModel(client),
    orgOwnerGrant: new OrgOwnerGrantModel(client),
    orgGrant: new OrgGrantModel(client),
    orgChartEdge: new OrgChartEdgeModel(client),
    orgChartEdgeGrant: new OrgChartEdgeGrantModel(client),
    appLimit: new AppLimitModel(client),
    orgLimit: new OrgLimitModel(client),
    appStep: new AppStepModel(client),
    appAchievement: new AppAchievementModel(client),
    appProfileGrant: new AppProfileGrantModel(client),
    appProfileDefinitionGrant: new AppProfileDefinitionGrantModel(client),
    orgProfile: new OrgProfileModel(client),
    invite: new InviteModel(client),
    claimedInvite: new ClaimedInviteModel(client),
    orgInvite: new OrgInviteModel(client),
    orgClaimedInvite: new OrgClaimedInviteModel(client),
    orgPermission: new OrgPermissionModel(client),
    appLevelRequirement: new AppLevelRequirementModel(client),
    appPermissionDefault: new AppPermissionDefaultModel(client),
    roleType: new RoleTypeModel(client),
    orgPermissionDefault: new OrgPermissionDefaultModel(client),
    cryptoAddress: new CryptoAddressModel(client),
    appLimitDefault: new AppLimitDefaultModel(client),
    orgLimitDefault: new OrgLimitDefaultModel(client),
    connectedAccount: new ConnectedAccountModel(client),
    phoneNumber: new PhoneNumberModel(client),
    membershipType: new MembershipTypeModel(client),
    appMembershipDefault: new AppMembershipDefaultModel(client),
    nodeTypeRegistry: new NodeTypeRegistryModel(client),
    orgMembershipDefault: new OrgMembershipDefaultModel(client),
    auditLog: new AuditLogModel(client),
    appLevel: new AppLevelModel(client),
    email: new EmailModel(client),
    appProfile: new AppProfileModel(client),
    user: new UserModel(client),
    hierarchyModule: new HierarchyModuleModel(client),
    query: createQueryOperations(client),
    mutation: createMutationOperations(client),
  };
}
