-- Revert: schemas/agentic_db_app_public/tables/conversation_chunks/triggers/conversation_chunks_enqueue_embedding_update_tg


DROP TRIGGER conversation_chunks_enqueue_embedding_update_tg ON agentic_db_app_public.conversation_chunks;


