-- Revert: schemas/agentic_db_user_identifiers_public/tables/phone_numbers/triggers/phone_numbers_immutable_number_tg


DROP TRIGGER phone_numbers_immutable_number_tg ON agentic_db_user_identifiers_public.phone_numbers;


