-- Revert: schemas/agentic_db_memberships_public/tables/org_membership_defaults/indexes/org_membership_defaults_updated_at_idx


DROP INDEX agentic_db_memberships_public.org_membership_defaults_updated_at_idx;


