-- Verify: schemas/agentic_db_memberships_private/trigger_fns/org_membership_validate_not_in_hierarchy_tg


SELECT verify_function('agentic_db_memberships_private.org_membership_validate_not_in_hierarchy_tg');


