-- Revert: schemas/agentic_db_memberships_public/tables/app_membership_defaults/indexes/app_membership_defaults_created_at_idx


DROP INDEX agentic_db_memberships_public.app_membership_defaults_created_at_idx;


