-- Revert: schemas/agent_db_memberships_private/tables/app_memberships_sprt/triggers/_00030_app_memberships_sprt_to_org_memberships_sprt


DROP TRIGGER _00030_app_memberships_sprt_to_org_memberships_sprt ON "agent_db_memberships_private".app_memberships_sprt;


