-- Revert: schemas/agent_db_profiles_public/tables/app_profile_definition_grants/indexes/app_profile_definition_grants_updated_at_idx


DROP INDEX "agent_db_profiles_public".app_profile_definition_grants_updated_at_idx;


