-- Revert: schemas/agentic_db_app_public/tables/calendar_event_notes/indexes/calendar_event_notes_calendar_event_id_idx


DROP INDEX agentic_db_app_public.calendar_event_notes_calendar_event_id_idx;


