-- Revert: schemas/agent_db_memberships_public/tables/org_membership_defaults/indexes/org_membership_defaults_created_at_idx


DROP INDEX agent_db_memberships_public.org_membership_defaults_created_at_idx;


