-- Revert: schemas/agentic_db_profiles_public/tables/org_profile_definition_grants/indexes/org_profile_definition_grants_created_at_idx


DROP INDEX "agentic_db_profiles_public".org_profile_definition_grants_created_at_idx;


